name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: create build folder
      run: mkdir build && mkdir build/obj
      
    - name: make autotests
      run: make autotests
      
    - name: run autotests
      run: ./build/autotests.exe
